/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sunnyslopes_lowydscavefinder_LowYDripstoneCaveFinderBridge */

#ifndef _Included_sunnyslopes_lowydscavefinder_LowYDripstoneCaveFinderBridge
#define _Included_sunnyslopes_lowydscavefinder_LowYDripstoneCaveFinderBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sunnyslopes_lowydscavefinder_LowYDripstoneCaveFinderBridge
 * Method:    riverSearch
 * Signature: (JIIIIIIFFIII)[I
 */
JNIEXPORT jintArray JNICALL Java_sunnyslopes_lowydscavefinder_LowYDripstoneCaveFinderBridge_riverSearch
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint, jint, jfloat, jfloat, jint, jint, jint);

/*
 * Class:     sunnyslopes_lowydscavefinder_LowYDripstoneCaveFinderBridge
 * Method:    getSearchProgress
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_sunnyslopes_lowydscavefinder_LowYDripstoneCaveFinderBridge_getSearchProgress
  (JNIEnv *, jclass);

/*
 * Class:     sunnyslopes_lowydscavefinder_LowYDripstoneCaveFinderBridge
 * Method:    getNowResult
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_sunnyslopes_lowydscavefinder_LowYDripstoneCaveFinderBridge_getNowResult
  (JNIEnv *, jclass);

/*
 * Class:     sunnyslopes_lowydscavefinder_LowYDripstoneCaveFinderBridge
 * Method:    pause
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_sunnyslopes_lowydscavefinder_LowYDripstoneCaveFinderBridge_pause
  (JNIEnv *, jclass);

/*
 * Class:     sunnyslopes_lowydscavefinder_LowYDripstoneCaveFinderBridge
 * Method:    resume
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_sunnyslopes_lowydscavefinder_LowYDripstoneCaveFinderBridge_resume
  (JNIEnv *, jclass);

/*
 * Class:     sunnyslopes_lowydscavefinder_LowYDripstoneCaveFinderBridge
 * Method:    stop
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_sunnyslopes_lowydscavefinder_LowYDripstoneCaveFinderBridge_stop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
